/**
  * GUIA PARA SER USAR O CODIGO DO FLOWATER 
  * PRIMEIRO, BAIXE AS SEGUINTES BIBLIOTECAS : Adafruit_PCD8544, FreqCount Adafruit GFX LibraryAdafruit 
  * OBS : AS BIBLIOTECAS DEVEM SER USADAS NO APLICATIVO DO ARDUINO, JUNTO COM O CODIGO, AMBOS DEVEM SER USADOS NO 
  * APLICATIVO IDE DO ADUINO 
 */

const add = () => { }